name: Build
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'docs/**'

jobs:
  build:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build frontend
        run: |
          cd internal/web/frontend
          npm install
          npm run build

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build binary
        run: |
          GOOS=linux GARCH=amd64 CGO_ENABLED=0 go build 
